name: .NET Core CI

on:
  push:
    branches: [ main, Develop, 'feat/**' ]
  pull_request:
    branches: [ main, Develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test with Coverage
      # Tady jsme pøidali filtry, které vyøadí všechno, co ti kazí prùmìr
      run: >
        dotnet test --no-build --verbosity normal 
        --collect:"XPlat Code Coverage" 
        -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude="[Stin-Semestral]Program,[*]AspNetCoreGeneratedDocument.*,[*]Stin_Semestral.Migrations.*,[*]Stin_Semestral.Data.*,[*]Stin_Semestral.View.*,[*]Stin_Semestral.Views.*"

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate Report
      run: |
        reportgenerator -reports:"**/TestResults/**/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:"MarkdownSummary;HtmlInline_AzurePipelines"

    - name: Upload coverage summary
      run: cat coveragereport/Summary.md >> $GITHUB_STEP_SUMMARY

    - name: Check Coverage Threshold
      shell: pwsh
      run: |
        $summary = Get-Content "coveragereport/Summary.md" -Raw
        if ($summary -match 'Branch coverage: (\d+\.?\d*)%') {
            $branchPercent = [double]$matches[1]
            Write-Host "Aktuální Branch Coverage: $branchPercent%"
            if ($branchPercent -lt 80) {
                Write-Error "Branch coverage je pod 80 %! Build selhal."
                exit 1
            }
        } else {
            Write-Error "Nepodaøilo se najít data o pokrytí."
            exit 1
        }